### ISSUE TITLE
Change local of debug icon

### ISSUE THREAD

**Issue by teacherlittletooth** [miltonbsn/brmodelo#319]
I suggest placing the debug icon on the lower left side of the screen, as it interferes with the logical model settings.
another suggestion is to create a comment box in the models.
Thank you and congrats for the excellent job!

**Comment by idmarjr** [comment]
Hi @teacherlittletooth  
Thanks a lot for the suggestions.

## Bug report button position

I will work on it as son as possible since it's a simple change with good life quality impact, specially when dealing with more complex models.

## Comment box

This is a feature that involves more thoughts and exploration in order to have it done.  
We have some ideas to introduce things like, model description as well as  description field to each entity but to be honest those are gonna take some time to be shipped

Still, I would like to have some more context from you on how do you see this _comment box_ working.  
If you can provide us with a screenshot, drawing, sketch or similar with more details on how you see this functionality in the system, it will be great. 

If you prefer, we can also schedule a chat via Google meets or Skype to have a chat about it.

---

P.S.: Our team also speaks Portuguese in case you feel more comfortable to discuss in pt-br

**Comment by idmarjr** [comment]
Since #321 is now merged into `development` branch I'm closing this issue. 

Please keep in mind it may take few weeks to ship this to production since we're working in some other matters that may block rollout to production for some time.


Regarding the _comment box_, this is a work in progress, part of our exploration designs at the moment. Unfortunately I cannot guarantee if this is going live to users.

Still, if/when this happens I will make sure to come back here to let you know :)
